# Generated by Django 4.2.11 on 2024-03-15 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trip_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
